#
# Module manifest for module 'NewManifest'
#
# Generated by: Thomas J. Malkewitz @dotps1 and Ben @beanska
#
# Generated on: 6/21/2016
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'HPWarranty.psm1'

# Version number of this module.
ModuleVersion = '0.0.0.0'

# ID used to uniquely identify this module
GUID = '4fb06411-cfeb-47fd-bf25-c0fbbdc6a09b'

# Author of this module
Author = 'Thomas J. Malkewitz @dotps1 and Ben @beanska'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2015 Thomas J. Malkewitz @dotps1 and Ben @beanska. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell Module designed to retrieve Hewlett-Packard Warranty Information.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = 
               'Get-HPIncWarrantyEntitlement Get-HPSystemInformationFromCMDB Get-HPEntWarrantyEntitlement'

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\en-US\LICENCE.md', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\en-US\about_HPWarranty.help.txt', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\en-US\HPWarranty.Help.xml', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\Public\Get-HPIncWarrantyEntitlement.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\Public\Get-HPSystemInformationFromCMDB.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\Public\Get-HPEntWarrantyEntitlment.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\Private\Get-HPProductNumberAndSerialNumber.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\Private\Invoke-HPIncSOAPRequest.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\Private\Invoke-HPEntSOAPRequest.ps1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\RequestTemplates\HPEntWarrantyRegistration.xml', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\RequestTemplates\HPEntWarrantyEntitlement.xml', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\RequestTemplates\HPIncWarrantyEntitlement.xml', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\HPWarranty.psd1', 
               'C:\Users\tmalkewitz\Documents\GitHub\HPWarranty\HPWarranty\HPWarranty\HPWarranty.psm1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Warranty','Hewlett-Packard','SOAP'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/dotps1/HPWarranty/master/LICENSE.md'

        # A URL to the main website for this project.
        ProjectUri = 'http://dotps1.github.io/HPWarranty'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = ''

    } # End of PSData hashtable
    
 } # End of PrivateData hashtable

# HelpInfo URI of this module
HelpInfoURI = 'https://raw.githubusercontent.com/dotps1/HPWarranty/master/en-US/HPWarranty.Help.xml'

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

